### ISSUE TITLE
Highlights add & override not working

### ISSUE THREAD

**Issue by notokrs** [NvChad/base46#185]
**Describe the bug**
Adding hl_override & hl_add in chadrc.lua doesn't seem to work

**To Reproduce**
1. Change highlights.lua file
2. Add hl_override & hl_add in chadrc.lua
3. overrided & added highlight not apllied 

**Expected behavior**
add & override highlight config applied

**Screenshots**
chadrc.lua
![2023-04-21_23-19](https://user-images.githubusercontent.com/79308398/233687924-d856752e-5048-4d39-8365-16a0a8f6507d.png)

highlights.lua
![2023-04-21_23-20](https://user-images.githubusercontent.com/79308398/233687931-d12f43af-76cd-4b34-9679-9f2b12706df7.png)

config not applied
![2023-04-21_23-29](https://user-images.githubusercontent.com/79308398/233687940-234ea39e-b377-4d3c-b833-cb2973d30bf6.png)

**Desktop (please complete the following information):**
 - Operating System: Artix Linux
 - Terminal: Kitty
 - Version of Neovim: Neovim 0.9.0 nightly

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/233847771-603ded53-2225-4d7a-abdb-03df60b7b99b.mp4

works. please save your file

**Comment by notokrs** [comment]
yeah, hl_override is not working until i change the theme and it's working now. But the hl_add to nvim-tree is not working, any suggestions?

**Comment by siduck** [comment]
@notokrs i dont get what you mean, please make a video!

**Comment by notokrs** [comment]
nvim tree opened folder name not applied

https://user-images.githubusercontent.com/79308398/234248191-4f529fc5-6bae-491e-92e7-c37ba80aa57c.mp4

**Comment by jamwil-cbre** [comment]
This still doesn't work. Perhaps because I'm still using v2.0 and there's a mismatch somewhere, but neither the override or the add are functional at all, on MacOS or Windows.

For instance, even the default override which sets `Comment` to italic has never worked. If I run `:Telescope highlights`, there is only `@comment`, which I can't figure out how to set.

**Comment by jamwil** [comment]
This still doesn't work. Perhaps because I'm still using v2.0 and there's a mismatch somewhere, but neither the override or the add are functional at all, on MacOS or Windows.

For instance, even the default override which sets `Comment` to italic has never worked. If I run `:Telescope highlights`, there is only `@comment`, which I can't figure out how to set.

**Comment by jamwil** [comment]
Got it working with this:

```lua
M.override = {
  Comment = {
    fg = "#999999",
    italic = true,
  },
  ["@comment"] = {
    fg = "#999999",
    italic = true,
  },
  LineNr = {
    fg = "#999999",
  },
  SignColumn = {
    fg = "#999999",
  },
}
```

There appears to be some cacheing going on here which can muddle things up. If you edit the config directly, it updates in place. I found that when managing dotfiles externally using something like chezmoi, I would need to purge my nvim data folder for the these changes to take hold.

**Comment by siduck** [comment]
@jamwil  just change your base46_cache path? go to your main init.lua file

`vim.fn.stdpath("config") .. "/base46_cache"`
